sudo: required
services:
  - docker

before_install:
  - docker build -t syam3222/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true syam3222/react-test npm test

after_success:
  - docker build -t syam3222/multi-client ./client
  - docker build -t syam3222/multi-nginx ./nginx
  - docker build -t syam3222/multi-server ./server
  - docker build -t syam3222/multi-worker ./worker
  # Take those images and upload to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push syam3222/multi-client
  - docker push syam3222/multi-nginx
  - docker push syam3222/multi-server
  - docker push syam3222/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-215155110326"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
